/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sci_Calculate;

import java.awt.event.KeyEvent;

/**
 *
 * @author ImrulHasan
 */
public class Sci_Calculator extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operations;
//    private Object Math;

    /**
     * Creates new form Sci_Calculator
     */
    public Sci_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Displaybar = new javax.swing.JTextField();
        btnCLR = new javax.swing.JButton();
        btnSQRT = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnBS = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnminus = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnmult = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btnsinh = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        btnXpY = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btntanh = new javax.swing.JButton();
        btnpie = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btncosh = new javax.swing.JButton();
        btnlnx = new javax.swing.JButton();
        btnXp2 = new javax.swing.JButton();
        btncbr = new javax.swing.JButton();
        btnrund = new javax.swing.JButton();
        btnbin = new javax.swing.JButton();
        btnhexa = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnplsmns = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnoctal = new javax.swing.JButton();
        btnXp3 = new javax.swing.JButton();
        btnEequal = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mfile = new javax.swing.JMenu();
        Mstand = new javax.swing.JMenuItem();
        Msci = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Displaybar.setBackground(new java.awt.Color(204, 204, 204));
        Displaybar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Displaybar.setForeground(new java.awt.Color(0, 153, 0));
        Displaybar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Displaybar.setToolTipText("");
        Displaybar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 2)));
        Displaybar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Displaybar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybarActionPerformed(evt);
            }
        });
        Displaybar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DisplaybarKeyTyped(evt);
            }
        });

        btnCLR.setBackground(new java.awt.Color(204, 0, 18));
        btnCLR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCLR.setText("C");
        btnCLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLRActionPerformed(evt);
            }
        });

        btnSQRT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSQRT.setText("√ ");
        btnSQRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSQRTActionPerformed(evt);
            }
        });

        btnplus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnplus.setText("+");
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });

        btnBS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBS.setForeground(new java.awt.Color(0, 153, 0));
        btnBS.setText("←");
        btnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnminus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnminus.setText("-");
        btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnmult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmult.setText("*");
        btnmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btndiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnlog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlog.setForeground(new java.awt.Color(0, 102, 102));
        btnlog.setText("log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        btnsin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsin.setForeground(new java.awt.Color(0, 0, 204));
        btnsin.setText("sin");
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });

        btnsinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsinh.setForeground(new java.awt.Color(0, 0, 204));
        btnsinh.setText("sinh");
        btnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinhActionPerformed(evt);
            }
        });

        btnFact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFact.setText("!");
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });

        btnXpY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXpY.setText("x^y");
        btnXpY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXpYActionPerformed(evt);
            }
        });

        btntan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntan.setForeground(new java.awt.Color(0, 0, 204));
        btntan.setText("tan");
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });

        btntanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntanh.setForeground(new java.awt.Color(0, 0, 204));
        btntanh.setText("tanh");
        btntanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanhActionPerformed(evt);
            }
        });

        btnpie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpie.setText(" π");
        btnpie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpieActionPerformed(evt);
            }
        });

        btncos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncos.setForeground(new java.awt.Color(0, 0, 204));
        btncos.setText("cos");
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });

        btncosh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncosh.setForeground(new java.awt.Color(0, 0, 204));
        btncosh.setText("cosh");
        btncosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoshActionPerformed(evt);
            }
        });

        btnlnx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlnx.setForeground(new java.awt.Color(0, 102, 102));
        btnlnx.setText("lnx");
        btnlnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlnxActionPerformed(evt);
            }
        });

        btnXp2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXp2.setText("x^2");
        btnXp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXp2ActionPerformed(evt);
            }
        });

        btncbr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncbr.setForeground(new java.awt.Color(0, 51, 204));
        btncbr.setText("cbr");
        btncbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncbrActionPerformed(evt);
            }
        });

        btnrund.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrund.setForeground(new java.awt.Color(0, 102, 204));
        btnrund.setText("rund");
        btnrund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrundActionPerformed(evt);
            }
        });

        btnbin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbin.setForeground(new java.awt.Color(0, 102, 102));
        btnbin.setText("bin");
        btnbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinActionPerformed(evt);
            }
        });

        btnhexa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhexa.setForeground(new java.awt.Color(0, 102, 102));
        btnhexa.setText("hexa");
        btnhexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhexaActionPerformed(evt);
            }
        });

        btnequal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnequal.setText("=");
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnplsmns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnplsmns.setText("±");
        btnplsmns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplsmnsActionPerformed(evt);
            }
        });

        btndot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndot.setText(".");
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });

        btnoctal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnoctal.setForeground(new java.awt.Color(0, 102, 102));
        btnoctal.setText("octal");
        btnoctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoctalActionPerformed(evt);
            }
        });

        btnXp3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXp3.setText("x^3");
        btnXp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXp3ActionPerformed(evt);
            }
        });

        btnEequal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEequal.setText("=");
        btnEequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEequalActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 0, 0));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Calculator");

        jMenuBar1.setForeground(new java.awt.Color(0, 51, 51));

        Mfile.setForeground(new java.awt.Color(0, 0, 51));
        Mfile.setText("File");
        Mfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfileActionPerformed(evt);
            }
        });

        Mstand.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        Mstand.setText("Standard");
        Mstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MstandActionPerformed(evt);
            }
        });
        Mfile.add(Mstand);

        Msci.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        Msci.setText("Scientific");
        Msci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsciActionPerformed(evt);
            }
        });
        Mfile.add(Msci);

        jMenuBar1.add(Mfile);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Displaybar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBS, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(btnCLR, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(btnSQRT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnmult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(btnplsmns, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXpY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btncbr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btntan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(btncos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btncosh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btntanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnbin, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(btnlnx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(btnrund))
                                    .addComponent(btnEequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnoctal)
                                    .addComponent(btnhexa))))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Displaybar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCLR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSQRT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpie, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncosh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXpY, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntanh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXp2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncbr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrund, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEequal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnplsmns, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXp3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnoctal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsciActionPerformed
        // TODO add your handling code here:
        this.setResizable(true);
        this.setSize(523, 400);     //Scientific
        Displaybar.setSize(486, 40);
    }//GEN-LAST:event_MsciActionPerformed

    private void btnlnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlnxActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.log10(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnlnxActionPerformed

    private void MstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MstandActionPerformed
        // TODO add your handling code here:
        this.setResizable(true);
        this.setSize(229, 400);         //Standard
    }//GEN-LAST:event_MstandActionPerformed

    private void DisplaybarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplaybarActionPerformed

    private void btnSQRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSQRTActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.sqrt(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnSQRTActionPerformed

    private void btnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSActionPerformed
        // TODO add your handling code here:
        String bsp= null;
        
        if(Displaybar.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(Displaybar.getText());
            strB.deleteCharAt(Displaybar.getText().length() - 1);
            bsp = strB.toString();
            Displaybar.setText(bsp);
        }
    }//GEN-LAST:event_btnBSActionPerformed

    private void btnCLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLRActionPerformed
        // TODO add your handling code here:
        Displaybar.setText("");
    }//GEN-LAST:event_btnCLRActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(Displaybar.getText());
        Displaybar.setText(null);
        operations=("+");
    }//GEN-LAST:event_btnplusActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn7.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn8.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn9.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn4.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn5.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn6.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn1.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn2.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn3.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        String iNum = Displaybar.getText() + btn0.getText();
        Displaybar.setText(iNum);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        // TODO add your handling code here:
        if(!Displaybar.getText().contains("."))
        {
            Displaybar.setText(Displaybar.getText() + btndot.getText());
        }
    }//GEN-LAST:event_btndotActionPerformed

    private void btnplsmnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplsmnsActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = ops * (-1);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnplsmnsActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        // TODO add your handling code here:
        String answer;
        secondnum = Double.parseDouble(Displaybar.getText());
        if(operations == "+")
        {
            result = firstnum +secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
    }//GEN-LAST:event_btnequalActionPerformed

    private void btnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(Displaybar.getText());
        Displaybar.setText(null);
        operations=("-");
    }//GEN-LAST:event_btnminusActionPerformed

    private void btnmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(Displaybar.getText());
        Displaybar.setText(null);
        operations=("*");
    }//GEN-LAST:event_btnmultActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(Displaybar.getText());
        Displaybar.setText(null);
        operations=("/");
    }//GEN-LAST:event_btndivActionPerformed

    private void btnXp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXp2ActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = (ops * ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnXp2ActionPerformed

    private void btnXp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXp3ActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = (ops * ops * ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnXp3ActionPerformed

    private void btnbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(Displaybar.getText());
       Displaybar.setText(Integer.toString(a,2));
    }//GEN-LAST:event_btnbinActionPerformed

    private void btnhexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhexaActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(Displaybar.getText());
       Displaybar.setText(Integer.toString(a,16));
    }//GEN-LAST:event_btnhexaActionPerformed

    private void btnoctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoctalActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(Displaybar.getText());
       Displaybar.setText(Integer.toString(a,8));
    }//GEN-LAST:event_btnoctalActionPerformed

    private void btnpieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpieActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = (3.1415926535897932384626433832795);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnpieActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.log(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnlogActionPerformed

    private void MfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MfileActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setResizable(true);
        this.setSize(237, 400);     //  normal
    }//GEN-LAST:event_formWindowActivated

    private void DisplaybarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisplaybarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_DisplaybarKeyTyped

    private void btncbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncbrActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.cbrt(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btncbrActionPerformed

    private void btnrundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrundActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.round(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnrundActionPerformed

    private void btnXpYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXpYActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.pow(ops,ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnXpYActionPerformed

    private void btnEequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEequalActionPerformed
        // TODO add your handling code here:
        String answer;
        secondnum = Double.parseDouble(Displaybar.getText());
        if(operations == "+")
        {
            result = firstnum +secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
        else if(operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            Displaybar.setText(answer);
        }
    }//GEN-LAST:event_btnEequalActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        // TODO add your handling code here:
        double ops;
        int fact = 1;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText())); 
        if(ops<0)
        {
            Displaybar.setText(String.valueOf(0));
        }
        else
        {
            
            for (int  c = 1 ; c <= ops ; c++ )
            fact = fact*c;
            Displaybar.setText(String.valueOf(fact));
        }
        
    }//GEN-LAST:event_btnFactActionPerformed

    private void btncoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoshActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.toRadians(ops);
        ops = Math.cosh(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btncoshActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.toRadians(ops);
        ops = Math.cos(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btncosActionPerformed

    private void btntanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanhActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.toRadians(ops);
        ops = Math.tan(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btntanhActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.toRadians(ops);
        ops = Math.tan(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btntanActionPerformed

    private void btnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinhActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.toRadians(ops);
        ops = Math.sinh(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnsinhActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        // TODO add your handling code here:
        double ops;
        ops = Double.parseDouble(String.valueOf(Displaybar.getText()));
        ops = Math.toRadians(ops);
        ops = Math.sin(ops);
        Displaybar.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnsinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sci_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sci_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sci_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sci_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sci_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Displaybar;
    private javax.swing.JMenu Mfile;
    private javax.swing.JMenuItem Msci;
    private javax.swing.JMenuItem Mstand;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBS;
    private javax.swing.JButton btnCLR;
    private javax.swing.JButton btnEequal;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton btnSQRT;
    private javax.swing.JButton btnXp2;
    private javax.swing.JButton btnXp3;
    private javax.swing.JButton btnXpY;
    private javax.swing.JButton btnbin;
    private javax.swing.JButton btncbr;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btncosh;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnhexa;
    private javax.swing.JButton btnlnx;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnminus;
    private javax.swing.JButton btnmult;
    private javax.swing.JButton btnoctal;
    private javax.swing.JButton btnpie;
    private javax.swing.JButton btnplsmns;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnrund;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btnsinh;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btntanh;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel label1;
    // End of variables declaration//GEN-END:variables
}
